name: artifact

on: [push]

env: 
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check put the code
        use: action/checkout@v2
      - name: upload the artifact
        use: action/upload-artifact@v2
        with: 
          name: ${{ env.ARTIFACT_NAME}}
          path: .
